export const AJAX_CALL_START = 'AJAX_CALL_START';
export const AJAX_CALL_END = 'AJAX_CALL_END';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const RECEIVE_DATA = 'RECEIVE_DATA';

export const ADD_NEW_CARD_SUCCESS = 'ADD_NEW_CARD_SUCCESS';
export const UPDATE_CARD_SUCCESS = 'UPDATE_CARD_SUCCESS';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const GET_ALL_CARDS_SUCCESS = 'GET_ALL_CARDS_SUCCESS';

export const ADD_NEW_DECK_SUCCESS = 'ADD_NEW_DECK_SUCCESS';
export const REMOVE_DECK_SUCCESS = 'REMOVE_DECK_SUCCESS';
export const SHOW_ADD_DECK = 'SHOW_ADD_DECK';
export const HIDE_ADD_DECK = 'HIDE_ADD_DECK';

export const SELECTED_DECK = 'SELECTED_DECK';

export const SET_DECK_ID = 'SET_DECK_ID';
export const GET_DECK_ID = 'GET_DECK_ID';

export const FILTER_CARDS = 'FILTER_CARDS';
export const SET_SHOW_BACK = 'SET_SHOW_BACK';

